spring.application.name=siaec-backend

server.port=8080
server.servlet.context-path=/v1

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/siaec
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=siaec_user
spring.datasource.password=123456

# spring.datasource.url=jdbc:h2:mem:siaecdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# springdoc.swagger-ui.path=/swagger-ui.html
# springdoc.api-docs.path=/v3/api-docs